# Capa 1: Contruir los archivos estaticos para el servidor web
FROM node:14.17 as builder
RUN mkdir -p /uno
WORKDIR /uno
COPY package.json package-lock.json /uno/
RUN npm install
COPY . /uno
RUN npm run ci:unoenty

# Capa 2: Servidor web NGINX
FROM nginx:1.21.0-alpine as production
ENV NODE_ENV production

# Copiamos los archivos generados en la capa 1 la ruta de HTML estatico de NGINX
COPY --from=builder /uno/packages/unoenty/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
