#Use node image as build layer
FROM node:14.17 as builder
RUN mkdir -p /uno
WORKDIR /uno
COPY . /uno
RUN npm run ci:unoenty
ENV PORT 80
ENV NODE_ENV production
EXPOSE 80 3667
WORKDIR /uno/packages/unoenty
RUN npm run start

#Use nginx as main layer
FROM nginx:1.21.0-alpine as production
ENV NODE_ENV production
COPY --from=builder /uno/packages/unoenty/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

