version: "3"
services:
  redis:
    image: redis
    restart: "no"
    ports:
        - 6333:6379
  uno-ui:
    build: 
      context: .
      dockerfile: Dockerfile.ui
    ports:
        - 5000:80
  uno-api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
        - 5001:80
